import argparse
import json
import collections

# Operation Classes
CLASS_ARITHMETIC = "ARITHMETIC"
CLASS_LOGIC = "LOGIC"
CLASS_SHIFT = "SHIFT"
CLASS_COMPARE = "COMPARE"

# Opcode Mapping to Classes
OP_CLASSES = {
    "ADD": CLASS_ARITHMETIC,
    "SUB": CLASS_ARITHMETIC,
    "AND": CLASS_LOGIC,
    "OR": CLASS_LOGIC,
    "XOR": CLASS_LOGIC,
    "SLL": CLASS_SHIFT,
    "SRL": CLASS_SHIFT,
    "SRA": CLASS_SHIFT,
    "SLT": CLASS_COMPARE,
    "SLTU": CLASS_COMPARE
}

# Opcode Encoding
OP_ENCODING = {
    "ADD": 0, "SUB": 1, "SLL": 2, "SLT": 3,
    "SLTU": 4, "XOR": 5, "SRL": 6, "SRA": 7,
    "OR": 8, "AND": 9
}

def analyze_trace(trace_file):
    with open(trace_file, "r") as f:
        ops = [line.strip().upper() for line in f if line.strip() and not line.startswith("#")]
    
    total_ops = len(ops)
    if total_ops == 0:
        raise ValueError("Empty trace file")

    op_counts = collections.Counter(ops)
    class_counts = collections.Counter([OP_CLASSES.get(op, "UNKNOWN") for op in ops])
    
    transitions = collections.defaultdict(collections.Counter)
    for i in range(len(ops) - 1):
        transitions[ops[i]][ops[i+1]] += 1
        
    return ops, total_ops, op_counts, class_counts, transitions

def generate_profile(trace_file, output_file, synth_random=False):
    if synth_random:
        # Generate synthetic generic profile
        total_ops = 1000
        op_freq = {op: 0.1 for op in OP_ENCODING}
        class_freq = {c: 0.25 for c in [CLASS_ARITHMETIC, CLASS_LOGIC, CLASS_SHIFT, CLASS_COMPARE]}
        trans_prob = {op: {next_op: 0.1 for next_op in OP_ENCODING} for op in OP_ENCODING}
        profile_name = "Synthetic Random Profile"
    else:
        ops, total_ops, op_counts, class_counts, transitions = analyze_trace(trace_file)
        profile_name = f"Measured Profile ({trace_file})"
        
        op_freq = {op: count / total_ops for op, count in op_counts.items()}
        class_freq = {cls: count / total_ops for cls, count in class_counts.items()}
        
        trans_prob = {}
        for op in OP_ENCODING:
            trans_prob[op] = {}
            total_trans = sum(transitions[op].values())
            for next_op in OP_ENCODING:
                if total_trans > 0:
                    trans_prob[op][next_op] = transitions[op].get(next_op, 0) / total_trans
                else:
                    trans_prob[op][next_op] = 1.0 / len(OP_ENCODING) # Fallback to uniform
                    
    # Generate a SV parameter file for inclusion
    sv_out = f"// Automatically generated by workload_profiler.py\n"
    sv_out += f"// Profile: {profile_name}\n\n"
    
    sv_out += "package workload_profile_pkg;\n"
    
    # Scale probabilities to 8-bit integers (0-255) for hardware thresholds
    sv_out += "    // Class Frequencies (Scaled 0-255)\n"
    for cls in [CLASS_ARITHMETIC, CLASS_LOGIC, CLASS_SHIFT, CLASS_COMPARE]:
        scaled_val = int(class_freq.get(cls, 0) * 255)
        sv_out += f"    localparam int unsigned WEIGHT_{cls} = {scaled_val};\n"
        
    sv_out += "\n    // Opcode Frequencies (Scaled 0-255)\n"
    for op in OP_ENCODING:
        scaled_val = int(op_freq.get(op, 0) * 255)
        sv_out += f"    localparam int unsigned FREQ_{op} = {scaled_val};\n"
        
    sv_out += "\n    // Transition Matrix (Scaled 0-255, 10x10 = 100 entries)\n"
    sv_out += "    localparam int unsigned TRANSITION_MATRIX [10][10] = '{\n"
    
    for op1, op1_code in OP_ENCODING.items():
        row = []
        for op2, op2_code in OP_ENCODING.items():
            prob = trans_prob.get(op1, {}).get(op2, 0.0)
            row.append(str(int(prob * 255)))
        sv_out += f"        '{{{', '.join(row)}}}"
        if op1_code < 9:
             sv_out += ",\n"
        else:
             sv_out += "\n"
    sv_out += "    };\n"
    sv_out += "endpackage\n"
    
    with open(output_file, "w") as f:
        f.write(sv_out)
        
    print(f"Profile generated and saved to {output_file}")
    
    # Save a JSON version as well
    json_data = {
        "profile_name": profile_name,
        "class_frequencies": class_freq,
        "operation_frequencies": op_freq,
        "transition_probabilities": trans_prob
    }
    with open(output_file.replace(".sv", ".json"), "w") as f:
        json.dump(json_data, f, indent=4)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Workload Profiler for WA-LP-BIST")
    parser.add_argument("--trace", type=str, help="Input instruction trace file (one opcode per line)")
    parser.add_argument("--output", type=str, default="workload_profile.sv", help="Output SystemVerilog package file")
    parser.add_argument("--synthetic", action="store_true", help="Generate synthetic uniform profile instead of measuring")
    args = parser.parse_args()
    
    generate_profile(args.trace, args.output, args.synthetic)
